### ISSUE TITLE
Add multiple hit possibility to pop-up targets

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#103]
As title says; multiple hit possibility for pop-up targets.

Being able to double tap targets would be great already!

**Comment by jonpas** [comment]
Targets currently supported are not impacted by `allowDamage`/`enableSimulation`, must intercept damage and do it manually to support this.

**Comment by jonpas** [comment]
Possibly found a way to do this, targets call a script on `hitPart` EH, script handles damage, animation and popping back up. Replacing that EH with a custom function would be the solution.

**Comment by SyMP2005** [comment]
would be extremely nice! :D
