### ISSUE TITLE
 Framework / module for Launcher course

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#105]
May function the same as weapons course, but I don't know if this is possible with the current module.

Also, IIRC there are some giant pop-up targets that could be used to practice with launchers. They were about the size of the front of car. (This was back from in usec so it could be that it was part of a mod we don't have.)
I'll confirm this ASAP, remind me if I don't.

**Comment by jonpas** [comment]
Give me classnames, I will check them out and see what's the best way to approach this, either add support to current module or make something new.

Though I don't really see how this would function as a framework, what would you expect it to do?

**Comment by SyMP2005** [comment]
I meant framework as in a new module if the current one wouldn't work. Probably misused the word...

![images](https://cloud.githubusercontent.com/assets/10323658/12109686/a9d84da2-b384-11e5-8ecc-8b387f50b84e.jpg)

Although like I said, I seriously doubt they're part of our modpack. Remember the wooden tanks? I think it's part of that.

**Comment by jonpas** [comment]
> what would you expect it to do?

There is no point measuring time or number od hits either, IMO.

**Comment by SyMP2005** [comment]
Well, it could mainly have hit recognition, and other targets would have to be protected from splash damage.

This *would* be applied from quite the distance, so imagine the targets being further apart and making splash damage irrelevant I guess.

*On the other hand*
I've just checked for the big pop up targets, and they're *not present.* 
Another option would be letting them fire launchers at "wrecks" which are available in many different objects and checking for hits manually. (Since it is quite easy to spot.)

If you agree with this, we can close this I guess.

**Comment by jonpas** [comment]
So you think no module is needed? Or does shooting range one do what you need?

**Comment by SyMP2005** [comment]
Probably not needed, can be done manually.

**Comment by jonpas** [comment]
Ok, closing.
