### ISSUE TITLE
Add sound to shooting range module

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#135]
Add following sounds to shooting course

`buzzer.ogg` - When the course starts.
`hit.ogg` - When a target is hit.
`hint.ogg` - When the course counts down the last 3 seconds.

I'll look up the paths when I get home.

**Comment by jonpas** [comment]
`CfgSounds`:
- `FD_Timer_F`
- `FD_Start_F`
- `FD_Finish_F`
