### ISSUE TITLE
Shooting range module error

### ISSUE THREAD

**Issue by Omnirock** [Theseus-Aegis/tac-a3-mods#153]
**Arma 3 Version:** Stable May 05 2015
**CBA Version:** 
**ACE3 Version:** 
**TAC Mods Version:** 

**Mods:**
TAC MODS REPO

**Description:**
- When setting countdown timer, if not set to a default value, an on screen error occurs (see link below). ACE3 will no longer function once this error occurs on init. 

**Steps to reproduce:**
- Change the shootingrange module's default countdown settings. 

**Where did the issue occur?**
- Singleplayer, Self-Hosted MP, Dedicated MP, Editor

**Placed Modules:**
- All modules placed on Olympus

**RPT log file:**
I'll get you one @jonpas , just poke me on Slack for screens and .rpt

**Comment by jonpas** [comment]
```
 5:53:50 Error in expression <
_defaultCountdownTime = 9;
};
{
if (_x < 5) then {
diag_log text format["[TAC] >
 5:53:50   Error position: << 5) then {
diag_log text format["[TAC] >
 5:53:50   Error <: Type String, expected Number,Not a Number
 5:53:50 File x\tac\addons\shootingrange\functions\fnc_create.sqf, line 30
```
