### ISSUE TITLE
Addable sound sources for shooting course

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#160]
Since you're working on TAC_shootingrange and because I'm annoying:

Can other sound sources be added to the course, so you can hear the `playSound` everywhere?
I think I mentioned this at some point and you said that's possible.

:+1: :hamster:

**Comment by jonpas** [comment]
What exactly are you requesting? Everywhere as on whole map (that doesn't make sense so I'll guess that's not it)?

**Comment by SyMP2005** [comment]
Everywhere on the course I meant, image that there would be speakers hanging on a couple positions.

http://www.thatcable.com/img/products/732_main.jpg

**Comment by jonpas** [comment]
Aha sure, probably best to add a field for sound sources (in addition to controller).

**Comment by SyMP2005** [comment]
:+1:

**Comment by jonpas** [comment]
Self-note:
- Separate function, controller and sound name passed (and volume if it's different - default value)
- Sound sources `setVariable` to controllers
