### ISSUE TITLE
Add framework for target randomization on the fly

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#190]
15 out of 30 targets have to pop up randomly on every course start.

**Comment by jonpas** [comment]
Will be an event to hook into it and probably some public functions.

**Comment by jonpas** [comment]
Function to get and set data (targets, triggers, ...) on a controller.

**Comment by jonpas** [comment]
Scratch that, simply an event with all appropriate data (always in same format), and maybe a setter function to validate input.
