### ISSUE TITLE
Remove health vehicle

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#45]
Remove restriction that only allows for "broken legs" to be healed in a vehicle/helicopter by the medic.

ACE setting. Is more a hassle at the moment than anything else. Especially with small groups.

**Comment by jonpas** [comment]
IIRC it's `GVAR(healHitPointAfterAdvBandage)`.

**Comment by jonpas** [comment]
This is not originating from `@tac_mods` but from `ACE_Settings` userconfig, fixed in TAC Modpack 1.3.0, for future, post non-`@tac_mods` related issues into repository `tac-a3-core`.
