### ISSUE TITLE
Create zeus module to add persistent vehicles

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#54]
Zeus module for creating persistent things

**Comment by jonpas** [comment]
- Client who drops the module in Zeus checks if `vehicleChronosID` already exists
- Server EH receives object
- Server EH calls:  
https://github.com/DavidCamre/Apollo/blob/master/src/com/apollo/persistence/Handler.java#L230  
`_newId = ["generateUniqueID"] call invoke_java_method;`
- Server EH sets variable with the generated ID

**Comment by jonpas** [comment]
Also test what happens with objects, eg. sandbags.
