### ISSUE TITLE
Items duplicated on Armory stashing

### ISSUE THREAD

**Issue by Dimaslg** [Theseus-Aegis/tac-a3-mods#72]
Some items gets "duplicated" when stashed on the Arsenal, they are not removed from inventory. You put the item, go to the Arsenal, stash it, it disapears from the arsenal to stash, but when you go back to check the inventory the item is still there so you can stash it again.

By now it happend with:

- [x] Sunglases (`CfgGlasses` items) -> CBATeam/CBA_A3#217
- [x] Binoculars / Laser Designator / Rangefinder

Ill be editing the thread if i find more items that get duplicated.

**Comment by jonpas** [comment]
I suspect this is a problem with removeXCargo functions from CBA/ChronosSQF.

**Comment by System98** [comment]
The following items also get duplicated:

343 Radios
Rangefinders

**Comment by jonpas** [comment]
Binoculars / Laser Designator / Rangefinder fixed in Chronos item database (aka Rory's fault).

@thomas_mueller please test this evening.

**Comment by System98** [comment]
They all still duplicate. The glasses do too. The ones I tested were:

- Aviator glasses
- Spectacle glasses

**Comment by jonpas** [comment]
Glasses duplicating is an issue from CBA (my functions though, so blame me), I submitted a fix PR (CBATeam/CBA_A3#217), will probably be in next CBA update.

**Comment by jonpas** [comment]
Binoculars confirmed fixed in Chronos.

Open a new issue if it happens again after CBA update.
