### ISSUE TITLE
Armory displays classnames in drop down menu's

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-mods#91]
![2015-12-15_00002](https://cloud.githubusercontent.com/assets/10323658/11824427/ca9bf946-a379-11e5-928b-2d57c2b7531f.jpg)

Occurs nearly all dropdown menu's.

**Comment by SyMP2005** [comment]
![2015-12-15_00001](https://cloud.githubusercontent.com/assets/10323658/11824703/a90e9318-a37b-11e5-975c-16f1418cb9f8.jpg)
![2015-12-15_00003](https://cloud.githubusercontent.com/assets/10323658/11824712/b3b5356a-a37b-11e5-8609-439c5d7c9fc1.jpg)
![2015-12-15_00004](https://cloud.githubusercontent.com/assets/10323658/11824714/b71e85ee-a37b-11e5-9dd5-8b3547a379e2.jpg)

You cannot retrieve the items listed in the subcategory menu.
Almost every subcategory dropdown has a classname listed as subcategory.

**Comment by jonpas** [comment]
Works fine locally, will test more later.

**Comment by jonpas** [comment]
Works fine, @SyMP2005 did something weird.
